### ISSUE TITLE
Something is breaking server-side rendering

### ISSUE THREAD

**Issue by AndrewIngram** [ffxsam/formous#8]
I haven't tracked down the cause. But I have a form that works fine in a client-only app, but causes server-side rendering to hang.

My form looks like this:

```javascript
/* @flow */

import React from 'react';
import Formous from 'formous';


const ErrorText = ({errorText}) =>
  <div style={{ color: '#f00' }}>{errorText}</div>;


class LoginForm extends React.Component {
  render() {
    const {
      fields: { username, password },
      formSubmit,
      onSubmit,
    } = this.props;

    console.log('username, password');

    return (
      <div>
        <form onSubmit={formSubmit(onSubmit)}>
          <div>
            <input
              placeholder="username or email address"
              type="text"
              value={username.value}
              {...username.events}
            />
          </div>
          <div>
            <input
              placeholder="your password"
              type="password"
              value={password.value}
              {...password.events}
            />
          </div>
          <div>
            <button type="submit">Submit</button>
          </div>
        </form>
      </div>
    );
  }
}


const formousOptions = {
  fields: {
    username: {
      name: 'username',
      tests: [
        {
          critical: true,
          failProps: { errorText: 'Your username or email address is required.' },
          test: value => value !== '',
        },
      ],
    },
    password: {
      name: 'password',
      tests: [
        {
          critical: true,
          failProps: { errorText: 'You must supply a password.' },
          test: value => value !== '',
        },
      ],
    },
  },
};

export default Formous(formousOptions)(LoginForm);
```

I'm rendering it in this component:

```javascript
const GlobalHeader = () => {
  return (
    <div className={styles.root}>
      <div className={styles.logo}>
        <Logo />
      </div>
      <div className={styles.locale}>
        <LocaleSwitcher />
      </div>
      <div className={styles.login}>
        <LoginForm />
      </div>
    </div>
  );
};
```

**Comment by ffxsam** [comment]
Ahh, interesting. I never work with SSR. Can you point me to an SSR boilerplate of some kind that I can install, so I can test it out and fix it?

**Comment by ffxsam** [comment]
@AndrewIngram Also, any errors you can share?

**Comment by kaatt** [comment]
```
ReferenceError: window is not defined
  at new _class2 (../node_modules/formous/lib/formous.js:54:9)
  at ReactCompositeComponentMixin._constructComponentWithoutOwner (../node_modules/react/lib/ReactCompositeComponent.js:307:27)
  at ReactCompositeComponentMixin._constructComponent (../node_modules/react/lib/ReactCompositeComponent.js:289:21)
  at ReactCompositeComponentMixin.mountComponent (../node_modules/react/lib/ReactCompositeComponent.js:192:21)
  at Object.ReactReconciler.mountComponent (../node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (../node_modules/react/lib/ReactMultiChild.js:242:44)
  at ReactDOMComponent.Mixin._createContentMarkup (../node_modules/react/lib/ReactDOMComponent.js:677:32)
  at ReactDOMComponent.Mixin.mountComponent (../node_modules/react/lib/ReactDOMComponent.js:535:29)
  at Object.ReactReconciler.mountComponent (../node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (../node_modules/react/lib/ReactMultiChild.js:242:44)
```

**Comment by kaatt** [comment]
Simply removing/commenting the `window.Formous` line fixes it. And everything works fine in the browser too.
